// src/components/App.jsx
import sass from '../scss/main.scss';
import React, {Component} from "react";


export class App extends Component {
    render() {
        return (
            <div>
                <img  className="logo" src={this.props.logo} alt=""/>
                <div>Webpack + {this.props.name}</div>
                <div className="menu">
                    {this.props.menu.map(link=>{ return <a className="item" key={link[0]} href={link[1]}>{link[0]}</a>})}
                </div>
            </div>
        )
    }
}

// src/components/App.vue
<template>
    <div id="app">
        <img :src="logo" alt="vue" class="logo">
        <div>
            Webpack + {{des}}
        </div>
        <div class="menu">
            <a class="item" v-for="link in links" :href="link[1]" :key="link[0]" v-text="link[0]"></a>
        </div>
    </div>
</template>

<script>
    import logo from '../img/vue.png';
    import data from '../data.json';
    import sass from '../scss/main.scss';
    export default {
        data(){
            return {
                logo:logo,
                des:"Vue",
                links:data.links

            }
        }
    }
</script>
